main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from qa import views as qa_views
# import debug_toolbar

handler404 = qa_views.handler404
handler500 = qa_views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profile.urls')),
    path('', include('qa.urls')),
    path('', include('notification.urls')),
    path('', include('tagbadge.urls')),
    path('', include('help.urls')),
    path('', include('review.urls')),
    path('', include('tools.urls')),
    path('accounts/',include('users.urls')),
    path('adminactions/', include('adminactions.urls')),
    path('martor/', include('martor.urls')),
    # path('__debug__/', include(debug_toolbar.urls)),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static 
from . import views
from django.views.decorators.cache import cache_page

app_name = 'profile'

urlpatterns = [

	path('', views.home, name='home'),

	path('activityPageTabProfile/<int:user_id>/<str:username>/', views.activityPageTabProfile, name='activityPageTabProfile'),

	path('ActivityTabSummary/<int:user_id>/<str:username>/', views.ActivityTabSummary, name='ActivityTabSummary'),

	path('usersPage/', views.usersPage, name='usersPage'),

	path('Ajax_searchTag/', views.Ajax_searchTag, name='Ajax_searchTag'),

	path('tagsPage/', views.tagsPage, name='tagsPage'),

	path('Ajax_searchUser/', views.Ajax_searchUser, name='Ajax_searchUser'),

	path('checkNotifications/', views.checkNotifications, name='checkNotifications'),

	path('userProfileEdit_Settings/<int:user_id>/', views.userProfileEdit_Settings, name='userProfileEdit_Settings'),

	path('email_html/',views.email_html,name='email_html'),

	path('tagPage/<int:user_id>/<int:tagbadge_id>/', views.tagPage, name='tagPage'),

	path('otherWithSame_Badge/<tag>/', views.otherWithSame_Badge, name='otherWithSame_Badge'),

	path('developerStoryTab/<int:user_id>/', views.developerStoryTab, name='developerStoryTab'),

	path('uploadPosition/<int:user_id>/', views.uploadPosition, name='uploadPosition'),

	path('addPositionAjax/<int:user_id>/', views.addPositionAjax, name='addPositionAjax'),

	path('select_BadgeTarget/<int:user_id>/', views.select_BadgeTarget, name='select_BadgeTarget'),

	path('activitAnswers/<int:user_id>/<str:username>/', views.activitAnswers, name='activitAnswers'),

	path('questionsActivity/<int:user_id>/<str:username>/', views.questionsActivity, name='questionsActivity'),

	path('tagsActivity/<int:user_id>/<str:username>/', views.tagsActivity, name='tagsActivity'),

	path('badgesActivity/<int:user_id>/<str:username>/', views.badgesActivity, name='badgesActivity'),

	path('bountiesActivity/<int:user_id>/<str:username>/', views.bountiesActivity, name='bountiesActivity'),

	path('bookmarksActivity/<int:user_id>/<str:username>/', views.bookmarksActivity, name='bookmarksActivity'),

	path('allActionsActivity/<int:user_id>/<str:username>/', views.allActionsActivity, name='allActionsActivity'),

	path('flag_summary/<int:user_id>/<str:username>/', views.flag_summary, name='flag_summary'),

	path('reputationActivity/<int:user_id>/<str:username>/', views.reputationActivity, name='reputationActivity'),

	path('Votes_castActivity/<int:user_id>/<str:username>/', views.Votes_castActivity, name='Votes_castActivity'),

	path('EditProfileAjaxForm/<int:user_id>/', views.EditProfileAjaxForm, name='EditProfileAjaxForm'),

	path('editProfile_JobPreAjax_Form/<int:user_id>/', views.editProfile_JobPreAjax_Form, name='editProfile_JobPreAjax_Form'),

	path('userProfileJonPrefrences_Settings/<int:user_id>/', views.userProfileJonPrefrences_Settings, name='userProfileJonPrefrences_Settings'),

	path('userProfileEdit_Email_Settings/<int:user_id>/', views.userProfileEdit_Email_Settings, name='userProfileEdit_Email_Settings'),

	path('editProfile_EditEmail_AjaxForm/<int:user_id>/', views.editProfile_EditEmail_AjaxForm, name='editProfile_EditEmail_AjaxForm'),

	path('loadQuestion_div/<int:question_id>/', views.loadQuestion_div, name='loadQuestion_div'),

	path('loadAnswer_div/<int:answer_id>/', views.loadAnswer_div, name='loadAnswer_div'),

	path('searchTagFromQuery/', views.searchTagFromQuery, name='searchTagFromQuery'),

	path('bountied_home/', views.bountied_home, name='bountied_home'),

	path('hot_q_day_home/', views.hot_q_day_home, name='hot_q_day_home'),

	path('hot_q_week_home/', views.hot_q_week_home, name='hot_q_week_home'),

	path('hot_q_month_home/', views.hot_q_month_home, name='hot_q_month_home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .  import views
from django.conf import settings
from django.conf.urls.static import static 
from .feeds import LatestQuestionFeed

app_name = 'qa'

urlpatterns = [

	path('new_question/', views.new_question, name='new_question'),

	path('questionDetailView/<int:pk>/', views.questionDetailView, name='questionDetailView'),

	path('questions/', views.questions, name='questions'),

	path('edit_question/<int:question_id>/', views.edit_question, name='edit_question'),

	path('question_upvote_downvote/<int:question_id>/', views.question_upvote_downvote, name='question_upvote_downvote'),

	path('mark_accepted/<int:question_id>/<int:answer_id>/', views.mark_accepted, name='mark_accepted'),

	path('bookmarkIt/<int:question_id>/', views.bookmarkIt, name='bookmarkIt'),

	path('BountiedQuestions/<query>', views.BountiedQuestions, name='BountiedQuestions'),

	path('answer_upvote_downvote/<int:answer_id>/', views.answer_upvote_downvote, name='answer_upvote_downvote'),

	path('awardBounty/<int:question_id>/<int:answer_id>/', views.awardBounty, name='awardBounty'),

	path('removeProtection/<int:question_id>/', views.removeProtection, name='removeProtection'),

	path('save_comment/<int:question_id>/', views.save_comment, name='save_comment'),

	path('upvote_comment/<int:commentq_id>/', views.upvote_comment, name='upvote_comment'),

	path('edit_answer/<int:answer_id>/', views.edit_answer, name='edit_answer'),

	path('deleteQuestion/<int:question_id>/', views.deleteQuestion, name='deleteQuestion'),

	path('undeleteQuestion/<int:question_id>/', views.undeleteQuestion, name='undeleteQuestion'),

	path('validateQuestionTitle/', views.validateQuestionTitle, name='validateQuestionTitle'),

	path('reviewQuestion/', views.reviewQuestion, name='reviewQuestion'),

	path('timeline/<int:question_id>/', views.questionTimeline, name='questionTimeline'),

	path('answerTimeline/<int:answer_id>/', views.answerTimeline, name='answerTimeline'),

	path('end_bounty_thread/<int:id>/', views.end_bounty_thread, name='end_bounty_thread'),

	path('banUser/<int:user_id>/', views.banUser, name='banUser'),

	path('allActiveThreads/', views.allActiveThreads, name='allActiveThreads'),

	path('UnBanUser/<int:id>/', views.UnBanUser, name='UnBanUser'),

	path('bookmarkQuestion/<int:question_id>/', views.bookmarkQuestion, name='bookmarkQuestion'),

	path('flagComment/<int:commentq_id>/', views.flagComment, name='flagComment'),

	path('save_comment_answer/<int:answer_id>/', views.save_comment_answer, name='save_comment_answer'),

	path('FlagCommentAjax/<int:commentq_id>/', views.FlagCommentAjax, name='FlagCommentAjax'),

	path('AjaxBountyForm/<int:question_id>/', views.AjaxBountyForm, name='AjaxBountyForm'),

	path('AjaxCloseForm/<int:question_id>/', views.AjaxCloseForm, name='AjaxCloseForm'),

	path('ProtectQuestionAjax/<int:question_id>/', views.ProtectQuestionAjax, name='ProtectQuestionAjax'),

	path('getCommunityWikiAnswerDetails/<int:answer_id>/', views.getCommunityWikiAnswerDetails, name='getCommunityWikiAnswerDetails'),

	path('ReOpenVotesAjax/<int:question_id>/', views.ReOpenVotesAjax, name='ReOpenVotesAjax'),

	path('award_InformedBadge_OnScroll/', views.award_InformedBadge_OnScroll, name='award_InformedBadge_OnScroll'),

	path('tourPage/', views.tourPage, name='tourPage'),

	path('AjaxFlagForm/<int:question_id>/', views.AjaxFlagForm, name='AjaxFlagForm'),

	path('Ajax_searchUser_Moderators/', views.Ajax_searchUser_Moderators, name='Ajax_searchUser_Moderators'),

	# path('inlineTagEditing_Mod_Tools/<int:question_id>/', views.inlineTagEditing_Mod_Tools, name='inlineTagEditing_Mod_Tools'),

	path('InlineTagEditingForm/<int:question_id>/', views.InlineTagEditingForm, name='InlineTagEditingForm'),

	path('feed/', LatestQuestionFeed(), name='post_feed'),

	path('flag_answer_ajax/<int:answer_id>/', views.flag_answer_ajax, name='flag_answer_ajax'),

	path('answer_edit_history/<int:answer_id>/', views.answer_edit_history, name='answer_edit_history'),

	path('getQuestionEditHistory/<int:question_id>/', views.getQuestionEditHistory, name='getQuestionEditHistory'),

	path('delete_answer/<int:answer_id>/', views.delete_answer, name='delete_answer'),

	path('undelete_answer/<int:answer_id>/', views.undelete_answer, name='undelete_answer'),

	path('unansweredQuestions/<query>/', views.unansweredQuestions, name='unansweredQuestions'),

	path('activeQuestions/<query>/', views.activeQuestions, name='activeQuestions'),

	path('load_question_upvotes_downvotes/<int:question_id>/', views.load_question_upvotes_downvotes, name='load_question_upvotes_downvotes'),

	path('load_answer_upvotes_downvotes/<int:answer_id>/', views.load_answer_upvotes_downvotes, name='load_answer_upvotes_downvotes'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tagbadge/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'tagbadge'

urlpatterns = [

	path('badges/', views.badges, name='badges'),

	path('taggedItems/<int:tag_id>/<int:user_id>/', views.taggedItems, name='taggedItems'),

	path('taggedItemsFrom_All/<int:tag_id>/', views.taggedItemsFrom_All, name='taggedItemsFrom_All'),

]

templates/home/bountied_home.html
{% extends 'profile/base.html' %}
{% load static %}
{% load humanize %}
{% load qa_tags %}

{% block content %}

<!DOCTYPE html>

    <html class="html__responsive">

    <head>
      <title>Stack Overflow - Clone</title>
      <link rel="stylesheet" type="text/css" href="https://cdn.sstatic.net/Shared/stacks.css?v=15473555f232">
      <link rel="stylesheet" type="text/css" href="https://cdn.sstatic.net/Sites/stackoverflow/primary.css?v=de9fb8b74f61">
    </head>


    <body class="home-page unified-theme">
    <div id="notify-container"></div>
    <div id="custom-header"></div>

    <div class="container">
            


<div id="left-sidebar" data-is-here-when="md lg" class="left-sidebar js-pinned-left-sidebar ps-relative">
    <div class="left-sidebar--sticky-container js-sticky-leftnav">
        <nav role="navigation">
            <ol class="nav-links">
        <li class="youarehere">
            <a
               href="/"
               class="pl8 nav-links--link">
                    <div class="d-flex ai-center">
                        <div class="flex--item truncate">
                            Home
                        </div>
                    </div>
            </a>
        </li>
                <li>
                    <ol class="nav-links">
                            <li class="fs-fine tt-uppercase ml8 mt16 mb4 fc-light">Public</li>

        <li class="">
            <a id="nav-questions" href="{% url 'qa:questions' %}" class="pl8 nav-links--link -link__with-icon">
               <svg aria-hidden="true" class="svg-icon iconGlobe" width="18" height="18" viewBox="0 0 18 18">
                <path d="M9 1C4.64 1 1 4.64 1 9c0 4.36 3.64 8 8 8 4.36 0 8-3.64 8-8 0-4.36-3.64-8-8-8ZM8 15.32a6.46 6.46 0 01-4.3-2.74 6.46 6.46 0 01-.93-5.01L7 11.68v.8c0 .88.12 1.32 1 1.32v1.52Zm5.72-2c-.2-.66-1-1.32-1.72-1.32h-1v-2c0-.44-.56-1-1-1H6V7h1c.44 0 1-.56 1-1V5h2c.88 0 1.4-.72 1.4-1.6v-.33a6.45 6.45 0 013.83 4.51 6.45 6.45 0 01-1.51 5.73v.01Z"/>
              </svg>
               <span class="-link--channel-name">Questions</span>
            </a>
        </li>
                        

        <li class="">
            <a id="nav-tags" href="{% url 'profile:tagsPage' %}" class="nav-links--link">
              <div class="d-flex ai-center">
                <div class="flex--item truncate">Tags</div>
              </div>
            </a>
        </li>


        <li class="">
          <a id="nav-users" href="{% url 'profile:usersPage' %}" class="nav-links--link">
            <div class="d-flex ai-center"><div class="flex--item truncate">Users</div></div>
          </a>
        </li>



                    </ol>
                </li>
            </ol>
        </nav>
    </div>

</div>




        <div id="content" class="snippet-hidden">

            
<div id="mainbar">
    
    

            <div class="d-flex">
                <h1 class="flex--item fl1 fs-headline1">Bountied Questions</h1>
                <div class="ml12 aside-cta flex--item print:d-none">
                  <a href="{% url 'qa:new_question' %}" class="ws-nowrap s-btn s-btn__primary">Ask Question</a>
                </div>
            </div>


        <div class="d-flex ai-center mb16">
            <div class="flex--item fl1 fs-body3"></div>
            <div class="flex--item">
                <div class=" d-flex s-btn-group js-filter-btn">
                  <a class="youarehere  flex--item s-btn s-btn__muted s-btn__outlined" href="/" title="Questions that may be of interest to you based on your history and tag preference">Interesting</a>


                  <a class="flex--item is-selected s-btn s-btn__muted s-btn__outlined" href="{% url 'profile:bountied_home' %}" title="Questions with an active bounty" data-value="bounties"><span class="bounty-indicator-tab">{{questions.all.count}}</span>Bountied</a>


                  <a class="flex--item s-btn s-btn__muted s-btn__outlined" href="{% url 'profile:hot_q_day_home' %}" title="Questions with the most views, answers, and votes over the last few days">Hot</a>


                  <a class="flex--item s-btn s-btn__muted s-btn__outlined" href="{% url 'profile:hot_q_week_home' %}" title="Questions with the most views, answers, and votes this week">Week</a>


                  <a class="flex--item s-btn s-btn__muted s-btn__outlined" href="{% url 'profile:hot_q_month_home' %}" title="Questions with the most views, answers, and votes this month">Month</a>
                </div>
            </div>
        </div>


<div id="qlist-wrapper" class="flush-left">
    {% for question in questions %}
    <div id="question-mini-list">
        <div>
          <div class="question-summary narrow" id="question-summary-{{question.id}}">
              <div onclick="window.location.href='{{question.get_absolute_url}}'" class="cp">
                <div class="votes {% if question.is_answer_accepted %}answered-accepted{% endif %}">
                  <div class="mini-counts"><span title="{{question.calculate_UpVote_DownVote}} votes">{{question.calculate_UpVote_DownVote}}</span></div>
                  <div>vote{{question.calculate_UpVote_DownVote|pluralize}}</div>
                </div>

                <div class="status unanswered">
                  <div class="mini-counts"><span title="{{question.count_answers}} answers">{{question.count_answers}}</span></div>
                  <div>answer{{question.count_answers|pluralize}}</div>
                </div>

                <div class="views">
                  <div class="mini-counts"><span title="{{question.calculate_viewers}} views">{{question.calculate_viewers}}</span></div>
                  <div>view{{question.calculate_viewers|pluralize}}</div>
                </div>
              </div>

      <div class="summary">
        <h3><a href="{{question.get_absolute_url}}" class="question-hyperlink">{{question.title}}</a></h3>
        <div class="tags d-flex gs4 fw-wrap mt2 float-none lh-unset t-node&#xFB;js t-docker t-environment-variables">
            
            {% for tag in question.tags.all %}
            <a href="{% url 'tagbadge:taggedItemsFrom_All' tag.id %}" class="post-tag flex--item" title="show questions tagged &#39;node.js&#39;" rel="tag">{{tag}}</a>
            {% endfor %}
            
            <div class="flex--item started ml-auto mt0 as-center">
                <a href="/questions/70486092/cant-set-ubuntu-docker-environment-variables" class="started-link">asked
                  <span title="2021-12-26 11:29:38Z" class="relativetime">{{question.date|naturaltime}}</span>
                </a>
                <a href="#">{{question.post_owner}}</a> <span class="reputation-score" title="reputation score " dir="ltr">{{question.post_owner|calculate_reputation}}</span>
            </div>
        </div>
    </div>
    


</div>

        </div>
    </div>
{% endfor %}
</div>

    <br class="cbt"/>
    <h2 class="bottom-notice" data-loc="2">Looking for more? Browse the <a href="{% url 'qa:questions' %}">complete list of questions</a>, or <a href="{% url 'profile:tagsPage' %}">popular tags</a>. Help us answer <a href="/unanswered">unanswered questions</a>.</h2>

</div>
    <div id="sidebar">

<div class="s-sidebarwidget s-sidebarwidget__yellow s-anchors s-anchors__grayscale mb16">
    <ul class="d-block p0 m0">
                    <div class="s-sidebarwidget--header s-sidebarwidget__small-bold-text fc-light d:fc-black-900 bb bbw1">
                        The Overflow Blog
                    </div>
        <li class="s-sidebarwidget--item d-flex px16">
            <div class="flex--item1 fl-shrink0">
<svg aria-hidden="true" class="va-text-top svg-icon iconPencilSm" width="14" height="14" viewBox="0 0 14 14"><path d="m11.1 1.71 1.13 1.12c.2.2.2.51 0 .71L11.1 4.7 9.21 2.86l1.17-1.15c.2-.2.51-.2.71 0ZM2 10.12l6.37-6.43 1.88 1.88L3.88 12H2v-1.88Z"/></svg>            </div>
            <div class="flex--item wmn0 ow-break-word">
                <a href="#" data-ga="[&quot;community bulletin board&quot;,&quot;The Overflow Blog&quot;,&quot;https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/&quot;,null,null]">Best practices for writing code comments</a>
            </div>
        </li>
                    <div class="s-sidebarwidget--header s-sidebarwidget__small-bold-text fc-light d:fc-black-900 bb bbw1">
                        Featured on Meta
                    </div>
        <li class="s-sidebarwidget--item d-flex px16">
            <div class="flex--item1 fl-shrink0">
<div class="favicon favicon-stackexchangemeta" title="Meta Stack Exchange"></div>            </div>
            <div class="flex--item wmn0 ow-break-word">
                <a href="#">Providing a JavaScript API for userscripts</a>
            </div>
        </li>
                    <div class="s-sidebarwidget--header s-sidebarwidget__small-bold-text fc-light d:fc-black-900 bb bbw1">
                        Hot Meta Posts
                    </div>
        <li class="s-sidebarwidget--item d-flex px16">
            <div class="flex--item1 fl-shrink0">
                        <span class="fc-black-500" title="Vote score (upvotes - downvotes)">18</span>
            </div>
            <div class="flex--item wmn0 ow-break-word">
                <a href="#">How much effort looking for plagiarism is expected of a reviewer of a tag...</a>
            </div>
        </li>
    </ul>
</div>


    </div>

        </div>
    </div>


            <footer id="footer" class="site-footer js-footer" role="contentinfo">
        <div class="site-footer--container">
                <div class="site-footer--logo">
                    <i class="fab fa-stack-overflow fa-3x"></i>
                </div>
            <nav class="site-footer--nav">
                    <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                        <h5 class="-title"><a href="" class="" >Stack Overflow - Clone</a></h5>
                        <ul class="-list js-primary-footer-links">
                            <li class="-item"><a href="/questions" class=" -link" data-gps-track="footer.click({ location: 4, link: 16})">Questions</a></li>
                                <li class="-item"><a href="" class=" -link" >Jobs</a></li>
                                <li class="-item"><a href="" class=" -link" >Developer Jobs Directory</a></li>
                                     <li class="-item"><a href="" class=" -link" >Salary Calculator</a></li>
                                <li class="-item"><a href="" class=" -link" >Help</a></li>
                                <li class="-item"><a onclick='StackExchange.switchMobile("on")' class=" -link" >Mobile</a></li>
                        </ul>
                    </div>
                    <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                        <h5 class="-title"><a href="">Products</a></h5>
                        <ul class="-list">
                            <li class="-item"><a href="" class=" -link" 
                                                 
                                                >Teams</a></li>
                            <li class="-item"><a href="" class=" -link" >Talent</a></li>
                            <li class="-item"><a href="" class=" -link" >Advertising</a></li>
                            <li class="-item"><a href="" class=" -link">Enterprise</a></li>
                        </ul>
                    </div>
                <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                    <h5 class="-title"><a href="">Company</a></h5>
                    <ul class="-list">
                            <li class="-item"><a class=" -link" href="">About</a></li>
                        <li class="-item"><a class=" -link" href="">Press</a></li>
                            <li class="-item"><a class=" -link" href="">Work Here</a></li>
                        <li class="-item"><a class=" -link" href="">Legal</a></li>
                        <li class="-item"><a class=" -link" href="">Privacy Policy</a></li>
                        <li class="-item"><a class="-link" href="">Terms of Service</a></li>
                            <li class="-item"><a class=" -link"  href="">Contact Us</a></li>
                            <li class="-item" id="consent-footer-link"><a class="-link js-cookie-settings" href="#" data-consent-popup-loader="footer">Cookie Settings</a></li>
                        <li class="-item"><a class=" -link"  href="">Cookie Policy</a></li>
                    </ul>
                </div>
            </nav>
            <div class="site-footer--copyright fs-fine">
                <ul class="-list">
                    <li class="-item"><a class="-link" href="">Blog</a></li>
                    <li class="-item"><a href="" class="-link" >Facebook</a></li>
                    <li class="-item"><a href="" class="-link" >Twitter</a></li>
                    <li class="-item"><a href="" class="-link" >LinkedIn</a></li>
                    <li class="-item"><a href="" class="-link">Instagram</a></li>
                </ul>

                <p class="mt-auto mb24">
site design / logo &#169; 2021 Stack Exchange Inc; user contributions licensed under <a href="https://stackoverflow.com/help/licensing">cc by-sa</a>.                    <span id="svnrev">rev&nbsp;2021.11.12.40742</span>
                </p>
            </div>
        </div>

    </footer>

    <div id="onetrust-consent-sdk" class="d-none"></div>
    <div id="onetrust-banner-sdk" data-controller="s-modal"></div>
    <div id="ot-pc-content" class="d-none"></div>
    <div id="onetrust-style" class="d-none">&nbsp;</div>
    <div class="d-none js-consent-banner-version" data-consent-banner-version="baseline"></div>

    
    </body>
    </html>

{% endblock content %}