main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from qa import views as qa_views
# import debug_toolbar

handler404 = qa_views.handler404
handler500 = qa_views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profile.urls')),
    path('', include('qa.urls')),
    path('', include('notification.urls')),
    path('', include('tagbadge.urls')),
    path('', include('help.urls')),
    path('', include('review.urls')),
    path('', include('tools.urls')),
    path('accounts/',include('users.urls')),
    path('adminactions/', include('adminactions.urls')),
    path('martor/', include('martor.urls')),
    # path('__debug__/', include(debug_toolbar.urls)),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static 
from . import views
from django.views.decorators.cache import cache_page

app_name = 'profile'

urlpatterns = [

	path('', views.home, name='home'),

	path('activityPageTabProfile/<int:user_id>/<str:username>/', views.activityPageTabProfile, name='activityPageTabProfile'),

	path('ActivityTabSummary/<int:user_id>/<str:username>/', views.ActivityTabSummary, name='ActivityTabSummary'),

	path('usersPage/', views.usersPage, name='usersPage'),

	path('Ajax_searchTag/', views.Ajax_searchTag, name='Ajax_searchTag'),

	path('tagsPage/', views.tagsPage, name='tagsPage'),

	path('Ajax_searchUser/', views.Ajax_searchUser, name='Ajax_searchUser'),

	path('checkNotifications/', views.checkNotifications, name='checkNotifications'),

	path('userProfileEdit_Settings/<int:user_id>/', views.userProfileEdit_Settings, name='userProfileEdit_Settings'),

	path('email_html/',views.email_html,name='email_html'),

	path('tagPage/<int:user_id>/<int:tagbadge_id>/', views.tagPage, name='tagPage'),

	path('otherWithSame_Badge/<tag>/', views.otherWithSame_Badge, name='otherWithSame_Badge'),

	path('developerStoryTab/<int:user_id>/', views.developerStoryTab, name='developerStoryTab'),

	path('uploadPosition/<int:user_id>/', views.uploadPosition, name='uploadPosition'),

	path('addPositionAjax/<int:user_id>/', views.addPositionAjax, name='addPositionAjax'),

	path('select_BadgeTarget/<int:user_id>/', views.select_BadgeTarget, name='select_BadgeTarget'),

	path('activitAnswers/<int:user_id>/<str:username>/', views.activitAnswers, name='activitAnswers'),

	path('questionsActivity/<int:user_id>/<str:username>/', views.questionsActivity, name='questionsActivity'),

	path('tagsActivity/<int:user_id>/<str:username>/', views.tagsActivity, name='tagsActivity'),

	path('badgesActivity/<int:user_id>/<str:username>/', views.badgesActivity, name='badgesActivity'),

	path('bountiesActivity/<int:user_id>/<str:username>/', views.bountiesActivity, name='bountiesActivity'),

	path('bookmarksActivity/<int:user_id>/<str:username>/', views.bookmarksActivity, name='bookmarksActivity'),

	path('allActionsActivity/<int:user_id>/<str:username>/', views.allActionsActivity, name='allActionsActivity'),

	path('flag_summary/<int:user_id>/<str:username>/', views.flag_summary, name='flag_summary'),

	path('reputationActivity/<int:user_id>/<str:username>/', views.reputationActivity, name='reputationActivity'),

	path('Votes_castActivity/<int:user_id>/<str:username>/', views.Votes_castActivity, name='Votes_castActivity'),

	path('EditProfileAjaxForm/<int:user_id>/', views.EditProfileAjaxForm, name='EditProfileAjaxForm'),

	path('editProfile_JobPreAjax_Form/<int:user_id>/', views.editProfile_JobPreAjax_Form, name='editProfile_JobPreAjax_Form'),

	path('userProfileJonPrefrences_Settings/<int:user_id>/', views.userProfileJonPrefrences_Settings, name='userProfileJonPrefrences_Settings'),

	path('userProfileEdit_Email_Settings/<int:user_id>/', views.userProfileEdit_Email_Settings, name='userProfileEdit_Email_Settings'),

	path('editProfile_EditEmail_AjaxForm/<int:user_id>/', views.editProfile_EditEmail_AjaxForm, name='editProfile_EditEmail_AjaxForm'),

	path('loadQuestion_div/<int:question_id>/', views.loadQuestion_div, name='loadQuestion_div'),

	path('loadAnswer_div/<int:answer_id>/', views.loadAnswer_div, name='loadAnswer_div'),

	path('searchTagFromQuery/', views.searchTagFromQuery, name='searchTagFromQuery'),

	path('bountied_home/', views.bountied_home, name='bountied_home'),

	path('hot_q_day_home/', views.hot_q_day_home, name='hot_q_day_home'),

	path('hot_q_week_home/', views.hot_q_week_home, name='hot_q_week_home'),

	path('hot_q_month_home/', views.hot_q_month_home, name='hot_q_month_home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .  import views
from django.conf import settings
from django.conf.urls.static import static 
from .feeds import LatestQuestionFeed

app_name = 'qa'

urlpatterns = [

	path('new_question/', views.new_question, name='new_question'),

	path('questionDetailView/<int:pk>/', views.questionDetailView, name='questionDetailView'),

	path('questions/', views.questions, name='questions'),

	path('edit_question/<int:question_id>/', views.edit_question, name='edit_question'),

	path('question_upvote_downvote/<int:question_id>/', views.question_upvote_downvote, name='question_upvote_downvote'),

	path('mark_accepted/<int:question_id>/<int:answer_id>/', views.mark_accepted, name='mark_accepted'),

	path('bookmarkIt/<int:question_id>/', views.bookmarkIt, name='bookmarkIt'),

	path('BountiedQuestions/<query>', views.BountiedQuestions, name='BountiedQuestions'),

	path('answer_upvote_downvote/<int:answer_id>/', views.answer_upvote_downvote, name='answer_upvote_downvote'),

	path('awardBounty/<int:question_id>/<int:answer_id>/', views.awardBounty, name='awardBounty'),

	path('removeProtection/<int:question_id>/', views.removeProtection, name='removeProtection'),

	path('save_comment/<int:question_id>/', views.save_comment, name='save_comment'),

	path('upvote_comment/<int:commentq_id>/', views.upvote_comment, name='upvote_comment'),

	path('edit_answer/<int:answer_id>/', views.edit_answer, name='edit_answer'),

	path('deleteQuestion/<int:question_id>/', views.deleteQuestion, name='deleteQuestion'),

	path('undeleteQuestion/<int:question_id>/', views.undeleteQuestion, name='undeleteQuestion'),

	path('validateQuestionTitle/', views.validateQuestionTitle, name='validateQuestionTitle'),

	path('reviewQuestion/', views.reviewQuestion, name='reviewQuestion'),

	path('timeline/<int:question_id>/', views.questionTimeline, name='questionTimeline'),

	path('answerTimeline/<int:answer_id>/', views.answerTimeline, name='answerTimeline'),

	path('end_bounty_thread/<int:id>/', views.end_bounty_thread, name='end_bounty_thread'),

	path('banUser/<int:user_id>/', views.banUser, name='banUser'),

	path('allActiveThreads/', views.allActiveThreads, name='allActiveThreads'),

	path('UnBanUser/<int:id>/', views.UnBanUser, name='UnBanUser'),

	path('bookmarkQuestion/<int:question_id>/', views.bookmarkQuestion, name='bookmarkQuestion'),

	path('flagComment/<int:commentq_id>/', views.flagComment, name='flagComment'),

	path('save_comment_answer/<int:answer_id>/', views.save_comment_answer, name='save_comment_answer'),

	path('FlagCommentAjax/<int:commentq_id>/', views.FlagCommentAjax, name='FlagCommentAjax'),

	path('AjaxBountyForm/<int:question_id>/', views.AjaxBountyForm, name='AjaxBountyForm'),

	path('AjaxCloseForm/<int:question_id>/', views.AjaxCloseForm, name='AjaxCloseForm'),

	path('ProtectQuestionAjax/<int:question_id>/', views.ProtectQuestionAjax, name='ProtectQuestionAjax'),

	path('getCommunityWikiAnswerDetails/<int:answer_id>/', views.getCommunityWikiAnswerDetails, name='getCommunityWikiAnswerDetails'),

	path('ReOpenVotesAjax/<int:question_id>/', views.ReOpenVotesAjax, name='ReOpenVotesAjax'),

	path('award_InformedBadge_OnScroll/', views.award_InformedBadge_OnScroll, name='award_InformedBadge_OnScroll'),

	path('tourPage/', views.tourPage, name='tourPage'),

	path('AjaxFlagForm/<int:question_id>/', views.AjaxFlagForm, name='AjaxFlagForm'),

	path('Ajax_searchUser_Moderators/', views.Ajax_searchUser_Moderators, name='Ajax_searchUser_Moderators'),

	# path('inlineTagEditing_Mod_Tools/<int:question_id>/', views.inlineTagEditing_Mod_Tools, name='inlineTagEditing_Mod_Tools'),

	path('InlineTagEditingForm/<int:question_id>/', views.InlineTagEditingForm, name='InlineTagEditingForm'),

	path('feed/', LatestQuestionFeed(), name='post_feed'),

	path('flag_answer_ajax/<int:answer_id>/', views.flag_answer_ajax, name='flag_answer_ajax'),

	path('answer_edit_history/<int:answer_id>/', views.answer_edit_history, name='answer_edit_history'),

	path('getQuestionEditHistory/<int:question_id>/', views.getQuestionEditHistory, name='getQuestionEditHistory'),

	path('delete_answer/<int:answer_id>/', views.delete_answer, name='delete_answer'),

	path('undelete_answer/<int:answer_id>/', views.undelete_answer, name='undelete_answer'),

	path('unansweredQuestions/<query>/', views.unansweredQuestions, name='unansweredQuestions'),

	path('activeQuestions/<query>/', views.activeQuestions, name='activeQuestions'),

	path('load_question_upvotes_downvotes/<int:question_id>/', views.load_question_upvotes_downvotes, name='load_question_upvotes_downvotes'),

	path('load_answer_upvotes_downvotes/<int:answer_id>/', views.load_answer_upvotes_downvotes, name='load_answer_upvotes_downvotes'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/forms.py
from django import forms
from .models import Question,Answer,Bounty,ProtectQuestion
from .models import BannedUser

class InlineTagEditForm(forms.ModelForm):

	class Meta:
		model = Question
		fields = ['tags']

class SearchForm(forms.Form):
	noAnswers = forms.BooleanField(initial=False)

class BanUser_Form(forms.ModelForm):

	class Meta:
		model = BannedUser
		fields = ['banned_reasons', 'ban_till']

class BountyForm(forms.ModelForm):

	class Meta:
		model = Bounty
		fields = ['bounty_value','why_bounting']

class QuestionForm(forms.ModelForm):

	class Meta:
		model = Question
		fields = ['title','body','tags']

class AnswerForm(forms.ModelForm):

	class Meta:
		model = Answer
		fields = ['body','is_wiki_answer']

class UpdateQuestion(forms.ModelForm):

	class Meta:
		model = Question
		fields = ['title','body','tags','why_editing_question']

class EditAnswerForm(forms.ModelForm):

	class Meta:
		model = Answer
		fields = ['body','why_editing_answer']

# class ReviewAnswer(forms.ModelForm):

# 	class Meta:
# 		model = ReviewFirstAnswer
# 		fields = ['actions']

CHOICES=[('select1','select 1'),
         ('select2','select 2')]


class ProtectForm(forms.ModelForm):

	class Meta:
		model = ProtectQuestion
		fields = ['why_want_toProtect']

templates/qa/answer_edit_history.html
{% extends 'profile/base.html' %}
{% load humanize %}
{% load martortags %}

{% block content %}


<!DOCTYPE html>


    <html class="html__responsive ">

<style>

	a {
		text-decoration: none !important;
	}

	.slider {
	  padding: auto;
	  display: none;
	  /*background-color: lightblue;*/
	}

</style>

    <body class="unified-theme">
    <div id="notify-container"></div>
    <div id="custom-header"></div>
    <div class="container">



<div id="left-sidebar" data-is-here-when="md lg" class="left-sidebar js-pinned-left-sidebar ps-relative">
    <div class="left-sidebar--sticky-container js-sticky-leftnav">
        <nav role="navigation">
            <ol class="nav-links">
		        <li class="">
		            <a href="/" class="pl8 nav-links--link">
		                <div class="d-flex ai-center">
		                    <div class="flex--item truncate">
		                        Home
		                    </div>
		                </div>
		            </a>
		        </li>
                <li>
                    <ol class="nav-links">
                    	<li class="fs-fine tt-uppercase ml8 mt16 mb4 fc-light">Public</li>
				        <li class="">
				            <a id="nav-questions"
				               href="{% url 'qa:questions' %}"
				               class="pl8 nav-links--link -link__with-icon">
							<svg aria-hidden="true" class="svg-icon iconGlobe" width="18" height="18" viewBox="0 0 18 18"><path d="M9 1C4.64 1 1 4.64 1 9c0 4.36 3.64 8 8 8 4.36 0 8-3.64 8-8 0-4.36-3.64-8-8-8ZM8 15.32a6.46 6.46 0 01-4.3-2.74 6.46 6.46 0 01-.93-5.01L7 11.68v.8c0 .88.12 1.32 1 1.32v1.52Zm5.72-2c-.2-.66-1-1.32-1.72-1.32h-1v-2c0-.44-.56-1-1-1H6V7h1c.44 0 1-.56 1-1V5h2c.88 0 1.4-.72 1.4-1.6v-.33a6.45 6.45 0 013.83 4.51 6.45 6.45 0 01-1.51 5.73v.01Z"/></svg>
							<span class="-link--channel-name">Questions</span>
				            </a>
				        </li>
				        <li class="">
				            <a id="nav-tags" href="{% url 'profile:tagsPage' %}" class="nav-links--link">
				                    <div class="d-flex ai-center">
				                        <div class="flex--item truncate">
				                            Tags
				                        </div>
				                    </div>
				            </a>
				        </li>
				        <li class="">
				            <a id="nav-users" href="{% url 'profile:usersPage' %}" class="nav-links--link">
				                <div class="d-flex ai-center">
				                    <div class="flex--item truncate">
				                        Users
				                    </div>
				                </div>
				            </a>
				        </li>
                    </ol>
                </li>
            </ol>
        </nav>
    </div>
</div>


        <div id="content" class="snippet-hidden">
        	<div class="subheader">
    			<h1><a href="{{getAnswer.questionans.get_absolute_url}}#{{getAnswer.id}}" class="question-hyperlink">Return to Question</a></h1>
    		</div>
		<div class="js-revisions">

			{% for history in editHistory %}

            <div class="mb12 js-revision">
		        <div class="d-flex p4 ai-center gs4 bg-powder-100">
		            <div class="flex--item">
		                    <button type="button"
		                            class="s-btn s-btn__unset c-pointer openDiv" onclick="openSlide({{forloop.counter}})">
		                        <div class="d-flex ai-center py8 gs8 gsx fc-black-600 md:fd-column-reverse">
		                            <div class="flex--item">
		                                <svg aria-hidden="true" class="js-off-icon svg-icon iconArrowRightAlt" width="18" height="18" viewBox="0 0 18 18"><path d="M6.41 2 5 3.41 10.59 9 5 14.59 6.41 16l7-7-7-7Z"/></svg>
		                                <svg aria-hidden="true" class="js-on-icon d-none svg-icon iconArrowDownAlt" width="18" height="18" viewBox="0 0 18 18"><path d="m16.01 6.43-1.4-1.41L9 10.6 3.42 5l-1.4 1.42 7 7 7-7Z"/></svg>
		                            </div>
		                            <div class="flex--item w48 fs-headline1 fw-bold ta-left md:ta-center" title="revision 1">{{forloop.counter}}</div>
		                        </div>
		                    </button>
		            </div>
		            <div class="flex--item fl1 wmn1">
		                <div class="d-flex ai-center fw-wrap">
		                    <div class="flex--item">
		                        <span class="js-revision-comment"></span>
		                    </div>
		                </div>
		        		<div class="d-flex gs8 s-anchors s-anchors__muted fw-wrap pt8">
		                    <a href="{% url 'qa:edit_answer' getAnswer.id %}" class="flex--item" title="edit this revision">Edit</a>
		                    <a href="{{getAnswer.questionans.get_absolute_url}}#{{getAnswer.id}}"
		                       class="flex--item"
		                       title="link to this formatted revision">Link</a>
		                	<button type="button" class="flex--item s-btn s-btn__link js-full-link d-none">Full</button>
		        		</div>
				        <div class="d-none md:d-block mt8">
							<div class="s-user-card s-user-card__minimal">
						        <div class="s-user-card--time">
						            <time>Edited <span class="relativetime">{{history.history_date|naturaltime}}</span></time>
						        </div>

						        <a href="{{history.history_user.profile.get_absolute_url}}" class="s-avatar s-avatar__16 s-user-card--avatar" tabindex="-1" aria-hidden="true">
						        	<img src="{% if history.history_user.profile.profile_photo %}{{history.history_user.profile.profile_photo.url}}{% endif %}" class="s-avatar--image" alt="" />
						        </a>
						        <div class="s-user-card--info">
						        	<a href="{{history.history_user.profile.get_absolute_url}}" class="s-user-card--link lh-lg" >{{history.history_user}} <span class="ws-nowrap"></span></a>
						        </div>
							</div>
						</div>
		            </div>
		        </div>

		        <div id="panel-{{forloop.counter}}" class="slider">
		        	<div class="markdown-diff tex2jax_ignore">
                    <table class="full-diff ">
                    	<tr>
                    		<td class="s-prose content deleted"><div>{{history.prev_record.body|safe_markdown}}</div></td>

							<td class="s-prose content inserted"><div>{{history.next_record.body|safe_markdown}}</div></td>
						</tr>
					</table>
                </div>
        </div>
</div>

		{% endfor %}

		    	</div>
    		</div>
		</div>



<script>

	function openSlide(iD) {
		$(`#panel-${iD}`).slideToggle("fast");

	}

</script>


        </div>
    </div>


            <footer id="footer" class="site-footer js-footer" role="contentinfo">
        <div class="site-footer--container">
                <div class="site-footer--logo">
                    <i class="fab fa-stack-overflow fa-3x"></i>
                </div>
            <nav class="site-footer--nav">
                    <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                        <h5 class="-title"><a href="" class="" >Stack Overflow - Clone</a></h5>
                        <ul class="-list js-primary-footer-links">
                            <li class="-item"><a href="/questions" class=" -link" data-gps-track="footer.click({ location: 4, link: 16})">Questions</a></li>
                                <li class="-item"><a href="" class=" -link" >Jobs</a></li>
                                <li class="-item"><a href="" class=" -link" >Developer Jobs Directory</a></li>
                                     <li class="-item"><a href="" class=" -link" >Salary Calculator</a></li>
                                <li class="-item"><a href="" class=" -link" >Help</a></li>
                                <li class="-item"><a onclick='StackExchange.switchMobile("on")' class=" -link" >Mobile</a></li>
                        </ul>
                    </div>
                    <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                        <h5 class="-title"><a href="">Products</a></h5>
                        <ul class="-list">
                            <li class="-item"><a href="" class=" -link" 
                                                 
                                                >Teams</a></li>
                            <li class="-item"><a href="" class=" -link" >Talent</a></li>
                            <li class="-item"><a href="" class=" -link" >Advertising</a></li>
                            <li class="-item"><a href="" class=" -link">Enterprise</a></li>
                        </ul>
                    </div>
                <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                    <h5 class="-title"><a href="">Company</a></h5>
                    <ul class="-list">
                            <li class="-item"><a class=" -link" href="">About</a></li>
                        <li class="-item"><a class=" -link" href="">Press</a></li>
                            <li class="-item"><a class=" -link" href="">Work Here</a></li>
                        <li class="-item"><a class=" -link" href="">Legal</a></li>
                        <li class="-item"><a class=" -link" href="">Privacy Policy</a></li>
                        <li class="-item"><a class="-link" href="">Terms of Service</a></li>
                            <li class="-item"><a class=" -link"  href="">Contact Us</a></li>
                            <li class="-item" id="consent-footer-link"><a class="-link js-cookie-settings" href="#" data-consent-popup-loader="footer">Cookie Settings</a></li>
                        <li class="-item"><a class=" -link"  href="">Cookie Policy</a></li>
                    </ul>
                </div>
            </nav>
            <div class="site-footer--copyright fs-fine">
                <ul class="-list">
                    <li class="-item"><a class="-link" href="">Blog</a></li>
                    <li class="-item"><a href="" class="-link" >Facebook</a></li>
                    <li class="-item"><a href="" class="-link" >Twitter</a></li>
                    <li class="-item"><a href="" class="-link" >LinkedIn</a></li>
                    <li class="-item"><a href="" class="-link">Instagram</a></li>
                </ul>

                <p class="mt-auto mb24">
site design / logo &#169; 2021 Stack Exchange Inc; user contributions licensed under <a href="https://stackoverflow.com/help/licensing">cc by-sa</a>.                    <span id="svnrev">rev&nbsp;2021.11.12.40742</span>
                </p>
            </div>
        </div>

    </footer>
    <div id="onetrust-consent-sdk" class="d-none"></div>
    <div id="onetrust-banner-sdk" data-controller="s-modal"></div>
    <div id="ot-pc-content" class="d-none"></div>
    <div id="onetrust-style" class="d-none">&nbsp;</div>
    <div class="d-none js-consent-banner-version" data-consent-banner-version="baseline"></div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    </body>
    </html>

{% endblock content %}

templates/qa/banUser.html
{% extends 'profile/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}

<br>
<div class="col-sm-3">
<table class="table table-bordered " border="1">
  <tr>
    <td><small>Date</small></td>
    <td><small>Banned for</small></td>
    <td><small>Suspension Period</small></td>
    <td><small>Banned By</small></td>
    <td><small>Completed ?</small></td>
  </tr>
{% for s in userBanHistory %}

<tr>

    <td>{{s.baned_at|naturaltime}}</td>
    <td><b>{{s.banned_reasons}}</b></td>
    <td>{{s.ban_till}}</td>
    <td>{{s.banned_by}}</td>
    <td>{% if s.is_banned %}Completed{% else %}<b>On Going</b>{% endif %}</td>

</tr>

{% endfor %}


</table>
</div>



<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ ban_form|crispy }}
        </table>
        <button type="submit">Save Changes</button>
    </form>
</div>

{% endblock content %}