main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from qa import views as qa_views
# import debug_toolbar

handler404 = qa_views.handler404
handler500 = qa_views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profile.urls')),
    path('', include('qa.urls')),
    path('', include('notification.urls')),
    path('', include('tagbadge.urls')),
    path('', include('help.urls')),
    path('', include('review.urls')),
    path('', include('tools.urls')),
    path('accounts/',include('users.urls')),
    path('adminactions/', include('adminactions.urls')),
    path('martor/', include('martor.urls')),
    # path('__debug__/', include(debug_toolbar.urls)),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static 
from . import views
from django.views.decorators.cache import cache_page

app_name = 'profile'

urlpatterns = [

	path('', views.home, name='home'),

	path('activityPageTabProfile/<int:user_id>/<str:username>/', views.activityPageTabProfile, name='activityPageTabProfile'),

	path('ActivityTabSummary/<int:user_id>/<str:username>/', views.ActivityTabSummary, name='ActivityTabSummary'),

	path('usersPage/', views.usersPage, name='usersPage'),

	path('Ajax_searchTag/', views.Ajax_searchTag, name='Ajax_searchTag'),

	path('tagsPage/', views.tagsPage, name='tagsPage'),

	path('Ajax_searchUser/', views.Ajax_searchUser, name='Ajax_searchUser'),

	path('checkNotifications/', views.checkNotifications, name='checkNotifications'),

	path('userProfileEdit_Settings/<int:user_id>/', views.userProfileEdit_Settings, name='userProfileEdit_Settings'),

	path('email_html/',views.email_html,name='email_html'),

	path('tagPage/<int:user_id>/<int:tagbadge_id>/', views.tagPage, name='tagPage'),

	path('otherWithSame_Badge/<tag>/', views.otherWithSame_Badge, name='otherWithSame_Badge'),

	path('developerStoryTab/<int:user_id>/', views.developerStoryTab, name='developerStoryTab'),

	path('uploadPosition/<int:user_id>/', views.uploadPosition, name='uploadPosition'),

	path('addPositionAjax/<int:user_id>/', views.addPositionAjax, name='addPositionAjax'),

	path('select_BadgeTarget/<int:user_id>/', views.select_BadgeTarget, name='select_BadgeTarget'),

	path('activitAnswers/<int:user_id>/<str:username>/', views.activitAnswers, name='activitAnswers'),

	path('questionsActivity/<int:user_id>/<str:username>/', views.questionsActivity, name='questionsActivity'),

	path('tagsActivity/<int:user_id>/<str:username>/', views.tagsActivity, name='tagsActivity'),

	path('badgesActivity/<int:user_id>/<str:username>/', views.badgesActivity, name='badgesActivity'),

	path('bountiesActivity/<int:user_id>/<str:username>/', views.bountiesActivity, name='bountiesActivity'),

	path('bookmarksActivity/<int:user_id>/<str:username>/', views.bookmarksActivity, name='bookmarksActivity'),

	path('allActionsActivity/<int:user_id>/<str:username>/', views.allActionsActivity, name='allActionsActivity'),

	path('flag_summary/<int:user_id>/<str:username>/', views.flag_summary, name='flag_summary'),

	path('reputationActivity/<int:user_id>/<str:username>/', views.reputationActivity, name='reputationActivity'),

	path('Votes_castActivity/<int:user_id>/<str:username>/', views.Votes_castActivity, name='Votes_castActivity'),

	path('EditProfileAjaxForm/<int:user_id>/', views.EditProfileAjaxForm, name='EditProfileAjaxForm'),

	path('editProfile_JobPreAjax_Form/<int:user_id>/', views.editProfile_JobPreAjax_Form, name='editProfile_JobPreAjax_Form'),

	path('userProfileJonPrefrences_Settings/<int:user_id>/', views.userProfileJonPrefrences_Settings, name='userProfileJonPrefrences_Settings'),

	path('userProfileEdit_Email_Settings/<int:user_id>/', views.userProfileEdit_Email_Settings, name='userProfileEdit_Email_Settings'),

	path('editProfile_EditEmail_AjaxForm/<int:user_id>/', views.editProfile_EditEmail_AjaxForm, name='editProfile_EditEmail_AjaxForm'),

	path('loadQuestion_div/<int:question_id>/', views.loadQuestion_div, name='loadQuestion_div'),

	path('loadAnswer_div/<int:answer_id>/', views.loadAnswer_div, name='loadAnswer_div'),

	path('searchTagFromQuery/', views.searchTagFromQuery, name='searchTagFromQuery'),

	path('bountied_home/', views.bountied_home, name='bountied_home'),

	path('hot_q_day_home/', views.hot_q_day_home, name='hot_q_day_home'),

	path('hot_q_week_home/', views.hot_q_week_home, name='hot_q_week_home'),

	path('hot_q_month_home/', views.hot_q_month_home, name='hot_q_month_home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .  import views
from django.conf import settings
from django.conf.urls.static import static 
from .feeds import LatestQuestionFeed

app_name = 'qa'

urlpatterns = [

	path('new_question/', views.new_question, name='new_question'),

	path('questionDetailView/<int:pk>/', views.questionDetailView, name='questionDetailView'),

	path('questions/', views.questions, name='questions'),

	path('edit_question/<int:question_id>/', views.edit_question, name='edit_question'),

	path('question_upvote_downvote/<int:question_id>/', views.question_upvote_downvote, name='question_upvote_downvote'),

	path('mark_accepted/<int:question_id>/<int:answer_id>/', views.mark_accepted, name='mark_accepted'),

	path('bookmarkIt/<int:question_id>/', views.bookmarkIt, name='bookmarkIt'),

	path('BountiedQuestions/<query>', views.BountiedQuestions, name='BountiedQuestions'),

	path('answer_upvote_downvote/<int:answer_id>/', views.answer_upvote_downvote, name='answer_upvote_downvote'),

	path('awardBounty/<int:question_id>/<int:answer_id>/', views.awardBounty, name='awardBounty'),

	path('removeProtection/<int:question_id>/', views.removeProtection, name='removeProtection'),

	path('save_comment/<int:question_id>/', views.save_comment, name='save_comment'),

	path('upvote_comment/<int:commentq_id>/', views.upvote_comment, name='upvote_comment'),

	path('edit_answer/<int:answer_id>/', views.edit_answer, name='edit_answer'),

	path('deleteQuestion/<int:question_id>/', views.deleteQuestion, name='deleteQuestion'),

	path('undeleteQuestion/<int:question_id>/', views.undeleteQuestion, name='undeleteQuestion'),

	path('validateQuestionTitle/', views.validateQuestionTitle, name='validateQuestionTitle'),

	path('reviewQuestion/', views.reviewQuestion, name='reviewQuestion'),

	path('timeline/<int:question_id>/', views.questionTimeline, name='questionTimeline'),

	path('answerTimeline/<int:answer_id>/', views.answerTimeline, name='answerTimeline'),

	path('end_bounty_thread/<int:id>/', views.end_bounty_thread, name='end_bounty_thread'),

	path('banUser/<int:user_id>/', views.banUser, name='banUser'),

	path('allActiveThreads/', views.allActiveThreads, name='allActiveThreads'),

	path('UnBanUser/<int:id>/', views.UnBanUser, name='UnBanUser'),

	path('bookmarkQuestion/<int:question_id>/', views.bookmarkQuestion, name='bookmarkQuestion'),

	path('flagComment/<int:commentq_id>/', views.flagComment, name='flagComment'),

	path('save_comment_answer/<int:answer_id>/', views.save_comment_answer, name='save_comment_answer'),

	path('FlagCommentAjax/<int:commentq_id>/', views.FlagCommentAjax, name='FlagCommentAjax'),

	path('AjaxBountyForm/<int:question_id>/', views.AjaxBountyForm, name='AjaxBountyForm'),

	path('AjaxCloseForm/<int:question_id>/', views.AjaxCloseForm, name='AjaxCloseForm'),

	path('ProtectQuestionAjax/<int:question_id>/', views.ProtectQuestionAjax, name='ProtectQuestionAjax'),

	path('getCommunityWikiAnswerDetails/<int:answer_id>/', views.getCommunityWikiAnswerDetails, name='getCommunityWikiAnswerDetails'),

	path('ReOpenVotesAjax/<int:question_id>/', views.ReOpenVotesAjax, name='ReOpenVotesAjax'),

	path('award_InformedBadge_OnScroll/', views.award_InformedBadge_OnScroll, name='award_InformedBadge_OnScroll'),

	path('tourPage/', views.tourPage, name='tourPage'),

	path('AjaxFlagForm/<int:question_id>/', views.AjaxFlagForm, name='AjaxFlagForm'),

	path('Ajax_searchUser_Moderators/', views.Ajax_searchUser_Moderators, name='Ajax_searchUser_Moderators'),

	# path('inlineTagEditing_Mod_Tools/<int:question_id>/', views.inlineTagEditing_Mod_Tools, name='inlineTagEditing_Mod_Tools'),

	path('InlineTagEditingForm/<int:question_id>/', views.InlineTagEditingForm, name='InlineTagEditingForm'),

	path('feed/', LatestQuestionFeed(), name='post_feed'),

	path('flag_answer_ajax/<int:answer_id>/', views.flag_answer_ajax, name='flag_answer_ajax'),

	path('answer_edit_history/<int:answer_id>/', views.answer_edit_history, name='answer_edit_history'),

	path('getQuestionEditHistory/<int:question_id>/', views.getQuestionEditHistory, name='getQuestionEditHistory'),

	path('delete_answer/<int:answer_id>/', views.delete_answer, name='delete_answer'),

	path('undelete_answer/<int:answer_id>/', views.undelete_answer, name='undelete_answer'),

	path('unansweredQuestions/<query>/', views.unansweredQuestions, name='unansweredQuestions'),

	path('activeQuestions/<query>/', views.activeQuestions, name='activeQuestions'),

	path('load_question_upvotes_downvotes/<int:question_id>/', views.load_question_upvotes_downvotes, name='load_question_upvotes_downvotes'),

	path('load_answer_upvotes_downvotes/<int:answer_id>/', views.load_answer_upvotes_downvotes, name='load_answer_upvotes_downvotes'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'review'

urlpatterns = [

	path('review_FirstAns/<int:answer_id>/', views.review_FirstAns, name='review_FirstAns'),

	path('review_answer_page/', views.review_answer_page, name='review_answer_page'),

	path('editFromReview/<int:answer_id>/', views.editFromReview, name='editFromReview'),

    path('post/ajax/EditAllowanceAjaxForm/<int:answer_id>/', views.EditAllowanceAjaxForm, name = "EditAllowanceAjaxForm"),

    path('post/ajax/EditQuestionAjax/<int:question_id>/', views.EditQuestionAjax, name = "EditQuestionAjax"),

    path('review_FirstQns/<int:question_id>/', views.review_FirstQns, name='review_FirstQns'),

    path('review_LateAnswers/<int:answer_id>/', views.review_LateAnswers, name='review_LateAnswers'),

    # path('reviewEdited_questions/<int:questionedit_id>/', views.reviewEdited_questions, name='reviewEdited_questions'),

    path('reviewClosedQuestions/<int:reviewclosevotes_id>/', views.reviewClosedQuestions, name='reviewClosedQuestions'),

    path('reOpen_Question_Review/<int:reviewquestionreopenvotes_id>/', views.reOpen_Question_Review, name='reOpen_Question_Review'),

    # path('edit_in_Closing/<int:question_id>/', views.edit_in_Closing, name='edit_in_Closing'),

    path('edit_in_Closing_Ajax/<int:question_id>/', views.edit_in_Closing_Ajax, name='edit_in_Closing_Ajax'),

    # path('reviewCloseInThis/<int:reviewclosevotes_id>/', views.reviewCloseInThis, name='reviewCloseInThis'),

    # path('reOpenReview/<int:reviewquestionreopenvotes_id>/', views.reOpenReview, name='reOpenReview'),

    path('retract_Close_Flag/<int:question_id>/', views.retract_Close_Flag, name='retract_Close_Flag'),

    path('reviewSuggesstedEdit/<int:reviewquestionedit_id>/', views.reviewSuggesstedEdit, name='reviewSuggesstedEdit'),

    path('reviewFlagPosts/<int:reviewflagpost_id>/', views.reviewFlagPosts, name='reviewFlagPosts'),

    path('reviewLowQualityPosts/<int:reviewlowqualityposts_id>/', views.reviewLowQualityPosts, name='reviewLowQualityPosts'),

    path('reviewFlagComments/<int:reviewflagcomment_id>/', views.reviewFlagComments, name='reviewFlagComments'),

    path('Edit_Q_In_SuggesstedEdits/<int:question_id>/', views.Edit_Q_In_SuggesstedEdits, name='Edit_Q_In_SuggesstedEdits'),

    path('Edit_Answer_In_SuggesstedEdits/<int:answer_id>/', views.Edit_Answer_In_SuggesstedEdits, name='Edit_Answer_In_SuggesstedEdits'),

    path('retract_Flag_Form/<int:question_id>/', views.retract_Flag_Form, name='retract_Flag_Form'),

    path('suggesstedEditHistory_Question/<int:reviewquestionedit_id>/', views.suggesstedEditHistory_Question, name='suggesstedEditHistory_Question'),

    path('questionCloseHistory/<int:reviewclosevotes_id>/', views.questionCloseHistory, name='questionCloseHistory'),

    path('flag_Posts_History/<int:reviewflagpost_id>/', views.flag_Posts_History, name='flag_Posts_History'),

    path('reOpen_Question_History/<int:reviewquestionreopenvotes_id>/', views.reOpen_Question_History, name='reOpen_Question_History'),

]

tagbadge/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'tagbadge'

urlpatterns = [

	path('badges/', views.badges, name='badges'),

	path('taggedItems/<int:tag_id>/<int:user_id>/', views.taggedItems, name='taggedItems'),

	path('taggedItemsFrom_All/<int:tag_id>/', views.taggedItemsFrom_All, name='taggedItemsFrom_All'),

]

tools/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static 
from . import views
from django.views.decorators.cache import cache_page

app_name = 'tools'

urlpatterns = [

	path('moderator_tools/', views.moderator_tools, name='moderator_tools'),

	path('deletePosts_Mod_Tools/', views.deletePosts_Mod_Tools, name='deletePosts_Mod_Tools'),

	path('question_with_extreme_votes_Mod_Tools/', views.question_with_extreme_votes_Mod_Tools, name='question_with_extreme_votes_Mod_Tools'),

	path('extreme_vote_on_answers/', views.answer_with_extreme_votes_Mod_Tools, name='extreme_ans_votes'),

	path('most_cmts_vws_edts/', views.questions_withmost_commts_vws_edts_Mod_Tools, name='most_cmts_vws_edts'),

	path('recentlyPrtcdQns_Mod_Tools/', views.recentlyPrtcdQns_Mod_Tools, name='recentlyPrtcdQns_Mod_Tools'),

	path('recentlyClsd_Mod_Tools/', views.recentlyClsd_Mod_Tools, name='recentlyClsd_Mod_Tools'),

	path('recently_reopnd_Mod_Tools/', views.recently_reopnd_Mod_Tools, name='recently_reopnd_Mod_Tools'),

	path('pending_Close_Vts_Mod_Tools/', views.pending_Close_Vts_Mod_Tools, name='pending_Close_Vts_Mod_Tools'),

	path('pending_reopen_Vts_Mod_Tools/', views.pending_reopen_Vts_Mod_Tools, name='pending_reopen_Vts_Mod_Tools'),

	path('newAns_To_oldQns_Mod_Tools/', views.newAns_To_oldQns_Mod_Tools, name='newAns_To_oldQns_Mod_Tools'),

]

tools/models.py
from django.db import models

# Create your models here.

templates/tools/deletePosts_Mod_Tools.html
{% extends 'profile/base.html' %}
{% load qa_tags %}
{% load humanize %}
{% load static %}

{% block content %}

<link href="{% static 'css/tools.css' %}" type="text/css" media="all" rel="stylesheet" />


<div class="heading"><h2>Deleted Questions</h2></div>


{% if results %}

    {% for result in results %}

    {% if result.post_owner %}

	<div class="question-summary narrow" id="question-summary-69681868">
		<div class="w48">&nbsp;</div>
		<div class="question-counts cp">
			<div class="votes">
				<div class="mini-counts" style="color: red">Q</div>
			</div>
			<div class="votes">
				<div class="mini-counts">{{result.calculate_UpVote_DownVote}}</div>
			</div>
		<div class="status {% if result.is_answer_accepted %}is_answer_accepted{% endif %}" title="one of the answers was accepted as the correct answer">
			<div class="mini-counts">{{result.count_answers}}</div>
		</div>
		<div class="views">
			<div class="mini-counts">{{result.calculate_viewers}}</div>
		</div>
	</div>
	<div class="summary">
		<h3><a href="{{result.get_absolute_url}}" target="_blank" class="question-hyperlink">{{result.title|truncatechars:20}}</a></h3>
		{% for tag in result.tags.all %}
		<div class="tags t-python t-django t-django-models t-django-views t-django-queryset">
			<a href="{% url 'tagbadge:taggedItemsFrom_All' tag.id %}" class="post-tag" title="show questions tagged &#39;{{tag}}&#39;" rel="tag">{{tag}}</a> 
            {% endfor %}
        </div>
        <div class="started">
        		<span class="answered">
        			<b>Asked by</b> - <a href="{{result.post_owner.profile.get_absolute_url}}">{{result.post_owner}}</a>
        		</span>
        			<div title="{{result.post_owner}}">
        				<img src="{% if result.post_owner.profile.profile_photo %} {{result.post_owner.profile.profile_photo.url}}{% endif %}" alt="" width="24" height="24" class="bar-sm">
        			</div>
                           <div class="-flair">
                                <span class="reputation-score" title="reputation score " dir="ltr">{{result.post_owner|calculate_reputation}}</span>
                                {% if result.post_owner|calculateGoldBadges %}
                                <span title="{{result.post_owner|calculateGoldBadges}} gold badges" aria-hidden="true">
                                    <span class="badge1"></span>
                                    <span class="badgecount">{{result.post_owner|calculateGoldBadges}}</span>
                                </span>
                                <span class="v-visible-sr">{{result.post_owner|calculateGoldBadges}} gold badges</span>
                                {% endif %}
                                {% if result.post_owner|calculatSilvereBadges %}

                                <span title="{{result.post_owner|calculatSilvereBadges}} silver badges" aria-hidden="true">
                                    <span class="badge2"></span>
                                    <span class="badgecount">{{result.post_owner|calculatSilvereBadges}}</span>
                                </span>
                                <span class="v-visible-sr">{{result.post_owner|calculatSilvereBadges}} silver badges</span>
                                {% endif %}
                                {% if result.post_owner|calculateBronzeBadges %}
                                <span title="{{result.post_owner|calculateBronzeBadges}} bronze badges" aria-hidden="true">
                                    <span class="badge3"></span>
                                    <span class="badgecount">{{result.post_owner|calculateBronzeBadges}}</span>
                                </span>
                                <span class="v-visible-sr">{{result.post_owner|calculateBronzeBadges}} bronze badges</span>
                                {% endif %}
                            </div>
        		<span class="deleted-time">
        			<b>Deleted</b> - {{result.date}}
        		</span>
        		<br>
            {% if result.lastEdited_by %}
            	<a href="{% url 'profile:activityPageTabProfile' result.q_edited_by.id result.q_edited_by.username %}">{{result.lastEdited_by}}
            	</a>
            {% endif %}
            <span class="reputation-score">
            		Asked {{result.date}}
            </span>
        </div>
    </div>
</div>

{% else %}


	<div class="question-summary narrow" id="question-summary-69681868">
		<div class="w48">&nbsp;</div>
		<div class="question-counts cp">
			<div class="votes">
				<div class="mini-counts" style="color: red">A</div>
			</div>
			<div class="votes">
				<div class="mini-counts {% if result.is_answer_accepted %}is_answer_accepted{% endif %}">{{result.countAllTheVotes}}</div>
			</div>
			<div class="votes">
				<div class="mini-counts"></div>
			</div>
		<div class="views">
			<div class="mini-counts">{{result.count_ViewsOf_Q}}</div>
		</div>
	</div>
	<div class="summary">
		<h3><a href="{{result.questionans.get_absolute_url}}#{{result.id}}" target="_blank" class="question-hyperlink">{{result.body|truncatechars:30}}</a></h3>
		{% for tag in result.questionans.tags.all %}
		<div class="tags t-python t-django t-django-models t-django-views t-django-queryset">
			<a href="{% url 'tagbadge:taggedItemsFrom_All' tag.id %}" class="post-tag" title="show questions tagged &#39;{{tag}}&#39;" rel="tag">{{tag}}
			</a> 
        </div>
        {% endfor %}
        <div class="started">
        		<span class="answered">
        			<b>Answered by</b> - <a href="{{result.answer_owner.profile.get_absolute_url}}">{{result.answer_owner}}</a>
        		</span>
        			<div title="{{result.answer_owner}}">
        				<img src="{% if result.answer_owner.profile.profile_photo %} {{result.answer_owner.profile.profile_photo.url}}{% endif %}" alt="" width="24" height="24" class="bar-sm">
        			</div>
                           <div class="-flair">
                                <span class="reputation-score" title="reputation score " dir="ltr">{{result.answer_owner|calculate_reputation}}</span>
                                {% if result.answer_owner|calculateGoldBadges %}
                                <span title="{{result.answer_owner|calculateGoldBadges}} gold badges" aria-hidden="true">
                                    <span class="badge1"></span>
                                    <span class="badgecount">{{result.answer_owner|calculateGoldBadges}}</span>
                                </span>
                                <span class="v-visible-sr">{{result.answer_owner|calculateGoldBadges}} gold badges</span>
                                {% endif %}
                                {% if result.answer_owner|calculatSilvereBadges %}

                                <span title="{{result.answer_owner|calculatSilvereBadges}} silver badges" aria-hidden="true">
                                    <span class="badge2"></span>
                                    <span class="badgecount">{{result.answer_owner|calculatSilvereBadges}}</span>
                                </span>
                                <span class="v-visible-sr">{{result.answer_owner|calculatSilvereBadges}} silver badges</span>
                                {% endif %}
                                {% if result.answer_owner|calculateBronzeBadges %}
                                <span title="{{result.answer_owner|calculateBronzeBadges}} bronze badges" aria-hidden="true">
                                    <span class="badge3"></span>
                                    <span class="badgecount">{{result.answer_owner|calculateBronzeBadges}}</span>
                                </span>
                                <span class="v-visible-sr">{{result.answer_owner|calculateBronzeBadges}} bronze badges</span>
                                {% endif %}
                            </div>
        		<span class="deleted-time">
        			<b>Deleted</b> - {{result.date}}
        		</span>
            {% if result.lastEdited_by %}
            	<a href="{% url 'profile:activityPageTabProfile' result.q_edited_by.id result.q_edited_by.username %}">{{result.lastEdited_by}}
            	</a>
            {% endif %}
            <br>
            <span class="reputation-score">
            		Answered {{result.date}}
            </span>
        </div>
    </div>
</div>

{% endif %}

{% endfor %}

{% else %}

<b class="no-post">No Deleted Posts</b>

{% endif %}






{% endblock content %}

templates/tools/moderatorTools.html
{% extends 'profile/base.html' %}
{% load static %}

{% block content %}

<link href="{% static 'css/tools.css' %}" type="text/css" media="all" rel="stylesheet" />



	<a class="tool-link" href="{% url 'tools:deletePosts_Mod_Tools' %}">• Deleted Posts</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:question_with_extreme_votes_Mod_Tools' %}">• Extreme Votes Questions</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:extreme_ans_votes' %}">• Extreme Votes Answers</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:most_cmts_vws_edts' %}">• Most Comments/Votes/Edit Questions</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:recentlyPrtcdQns_Mod_Tools' %}">• Protected Questions</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:recentlyClsd_Mod_Tools' %}">• Closed Questions</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:recently_reopnd_Mod_Tools' %}">• ReOpened Questions</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:pending_Close_Vts_Mod_Tools' %}">• Pending Close Votes</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:pending_reopen_Vts_Mod_Tools' %}">• Pending ReOpen Votes</a>
<br><br>

	<a class="tool-link" href="{% url 'tools:newAns_To_oldQns_Mod_Tools' %}">• New Answer to Old Questions</a>
<br><br>

	<a class="tool-link" href="#">• Suggested Edits to Posts</a>




{% endblock content %}